version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - PG_USER=todoapp
      - PG_PASSWORD=K4guy4S4m4
      - PG_DB=postgres
      - PG_HOST=tododb.cdm6ewu229mu.us-east-1.rds.amazonaws.com
      - PG_PORT=5432
      - PORT=5000
      - PGSSLMODE=require
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "5000:5000"
    networks:
      - todo-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
